### PR TITLE
Updated to Play 2.1.0

### PR DESCRIPTION
**Pull request by remeh**
- Updated dependencies (Jongo 0.3, mongo-driver 2.8.0, Play 2.1.0)
- Removed un-needed files which caused a buggy behavior with reversed routing in a project (like routes, Application controller)
- Modified the build configuration to not try to generate javadoc

### CODE REVIEW

**Comment by monsieurBelbo** [comment]
Hi @remeh 
I'm having the exact same issue. I've looked into your update, but still can't figure out what's causing the problem and couldn't fix it trying to replicate what you've done.
Could you please further explain what is the nature of the issue so I can fix it on my app?

Thanks in advance!

**Comment by remeh** [comment]
Hello @monsieurBelbo,

The main problem that I had is that a default Play 2.1 application comes with an Application controller and the jongo2-play-spike modules also had an Application controller declared in the same package `controllers`.

These two fellas were conflicting and so, Play was complaining when launched in dev mode. There were no problem in prod mode, probably because the class-loader doesn't behave the same.

You should look in the different modules used in your project whether they have some controllers declared in the same package as yours.

**Comment by monsieurBelbo** [comment]
Thanks for the prompt response, @remeh 

What does this mean? I can't have a controller named `Application` in my app?
Actually, I do have an `Application` controller (not the one from the default Play application), but how would I know if a module used in my project has a conflicting controller?

I might also add my app is not using jongo2-play-spike as a module, but it is including `play-jongo` as a dependency.

Here's a copy of my `Build.scala` if it adds any new info:

```
import sbt._
import Keys._
import play.Project._

object ApplicationBuild extends Build {

    val appName         = "rossirixweb"
    val appVersion      = "1.0-SNAPSHOT"

    val appDependencies = Seq(
        javaCore,
        javaJdbc,
        javaEbean,
        javaJpa,
        "org.apache.xmlrpc" % "xmlrpc" % "3.0",
        "commons-httpclient" % "commons-httpclient" % "3.1",
        "com.google.code.gson" % "gson" % "2.2.2",
        "junit" % "junit" % "4.11",
        "org.mongodb" % "mongo-java-driver" % "2.10.1",
        "uk.co.panaxiom" %% "play-jongo" % "0.3",
        "mysql" % "mysql-connector-java" % "5.1.22"
    )

    val main = play.Project(appName, appVersion, appDependencies).settings(
        // ...
    )
}
```

Any help will be very much appreciated!
Thanks!!

**Comment by bguerout** [comment]
Hi @remeh Is it solved by your pull-request : https://github.com/bguerout/jongo-play2-spike/pull/1 ?

**Comment by remeh** [comment]
Hey,
Yes I think that the pull-request #1 fix the problem of Controller conflicting for the jongo-play2-spike.
http://www.playframework.com/documentation/2.1.0/SBTSubProjects said 
"Note: in order to avoid naming collision, make sure your controllers, including the Assets controller in your subprojects are using a different name space than the main project"

**I'm may be wrong** but @monsieurBelbo you can still have conflicts with your other modules, especially if they were quickly created for Play 2 and if their Application controller weren't removed.

**Pull request merged**
